let armShopItemData = [
  {
    id: 1,
    img: "./images/armrest1.jpg",
    name: "Brown leather Arm-Rest",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 2499,
  },
  {
    id: 2,
    img: "./images/armrest2.jpg",
    name: "Chipped-Wood colored Leather Arm-Rest",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 4499,
  },
  {
    id: 3,
    img: "./images/armrest3.jpg",
    name: "Black leather Arm-Rest",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 3499,
  },
  {
    id: 4,
    img: "./images/armrest4.jpg",
    name: "Cream colored leather Arm-Rest",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 2999,
  },
  {
    id: 5,
    img: "./images/dash1.jpg",
    name: "White Daisy ",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 1499,
  },
  {
    id: 6,
    img: "./images/dash2.jpg",
    name: "Monkey couple",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 1999,
  },
  {
    id: 7,
    img: "./images/dash3.jpg",
    name: "Cool Airplane",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 1599,
  },
  {
    id: 8,
    img: "./images/dash4.jpg",
    name: "Cute decor",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 1299,
  },
  {
    id: 17,
    img: "./images/visor1.jpg",
    name: "Black",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 1499,
  },
  {
    id: 18,
    img: "./images/visor2.jpg",
    name: "Brown",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 1999,
  },
  {
    id: 19,
    img: "./images/visor3.jpg",
    name: "Mate Black",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 2599,
  },
  {
    id: 20,
    img: "./images/visor4.jpg",
    name: "Tinted-Black",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 2299,
  },
  {
    id: 9,
    img: "./images/perfume1.jpg",
    name: "Odonil",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 499,
  },
  {
    id: 10,
    img: "./images/perfume2.jpg",
    name: "Lavender",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 999,
  },
  {
    id: 11,
    img: "./images/perfume3.jpg",
    name: "Incense",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 1599,
  },
  {
    id: 12,
    img: "./images/perfume4.jpg",
    name: "Osmanthus",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 1299,
  },
  {
    id: 13,
    img: "./images/seat1.jpg",
    name: "Brown premium leather",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 5499,
  },
  {
    id: 14,
    img: "./images/seat2.jpg",
    name: "Oak leather",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 3999,
  },
  {
    id: 15,
    img: "./images/seat3.jpg",
    name: "Mate Black",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 4599,
  },
  {
    id: 16,
    img: "./images/seat4.jpg",
    name: "Neon-Black",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 3299,
  },
  {
    id: 21,
    img: "./images/steer1.jpg",
    name: "Gray premium leather",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 2499,
  },
  {
    id: 22,
    img: "./images/steer2.jpg",
    name: "Oak leather",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 3999,
  },
  {
    id: 23,
    img: "./images/steer3.jpg",
    name: "Premium Chipped oak",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 3599,
  },
  {
    id: 24,
    img: "./images/steer4.jpg",
    name: "Classic gray",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quasia ratione fuga, quidem consequuntur.",
    price: 2299,
  },
];
